# Generated by Django 3.2.9 on 2021-11-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_coding_skill',
            field=models.BooleanField(default=False),
        ),
    ]
